/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#4800a0",
        "primary-container": "#630ed4",
        "on-primary": "#ffffff",
        "on-primary-container": "#cdb4ff",
        "primary-fixed": "#eaddff",
        "primary-fixed-dim": "#d2bbff",
        "secondary": "#544fc0",
        "secondary-container": "#8f8bff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#241791",
        "secondary-fixed": "#e2dfff",
        "secondary-fixed-dim": "#c3c0ff",
        "tertiary": "#00402a",
        "tertiary-container": "#005a3c",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#85cfa9",
        "tertiary-fixed": "#a6f3cb",
        "tertiary-fixed-dim": "#8bd6af",
        "background": "#FBFAF2",
        "surface": "#FBFAF2",
        "surface-dim": "#d8dadc",
        "surface-bright": "#FBFAF2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#4a4455",
        "on-background": "#191c1e",
        "outline": "#7b7487",
        "outline-variant": "#ccc3d8",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#d2bbff",
        "surface-tint": "#732ee4",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "xxl": "80px",
        "gutter": "24px",
        "container-max": "1200px",
        "unit": "4px",
      },
      fontFamily: {
        "display": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-mono": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
  plugins: [],
}
